version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wwwResumeApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rbkyto0i2tp7"
s3_prefix = "wwwResumeApp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
