name: API gateway, AWS Lambda, AWS DynamoDB deployment for www_backend
#Triggers the workflow on push request events to main branch
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install program dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/custom_cors_check/requirements.txt
        pip install -r app/view_count/requirements.txt
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install test dependencies
      run: |
        pip install -r tests/requirements.txt
    - name: Run unit test
      run: |
        pytest tests/unit
    - name: SAM build
      uses: youyo/aws-sam-action/python3.8@master
      with:
        sam_command: build
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  us-east-1
    - name: Sam deploy
      run: |
        sam deploy --template template.yaml --stack-name wwwResumeAppBE --s3-bucket aws-cli-wwwresume-be-template --s3-prefix wwwResumeAppBE --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset --no-fail-on-empty-changeset
    - name: Run integration test
      run: |
        pytest tests/integration